### ISSUE TITLE
mnpaid is mnppsd in German version resulting in missing Add-ID 

### ISSUE THREAD

**Issue by miljukov-o** [SwissClinicalTrialOrganisation/secuTrialR#235]
If I'm correct, in the German set-up of the ExportSearchTool (trial in German), mnpaid is exported as mnpsd, resulting in missing Add-ID, unfortunately blocking the use of read_validation_overview.

https://github.com/SwissClinicalTrialOrganisation/secuTrialR/blob/fb551f60dee4a2e3fa6e769e128b82bdfc741f9e/R/read_secuTrial_raw.R#L86

**Comment by PatrickRWright** [comment]
Hi @miljukov-o `read_validation_overview()` is intended to read data from the validation report into R. The validation report is not retrieved via ExportSearchTool though, so maybe there is a misunderstanding here. You retrieve the validation report from the `Reports` section in DataCapture.

Also `mnpaid` being `mnpsd` in the German version doesn't ring any bell for me. Maybe you can give a little more context or even an example export?

**Comment by miljukov-o** [comment]
Dear @PatrickRWright  thank you very much for your reply. 
read_validation_overview() was just an example, where a missing mnpaid causes problems. 

I have to correct: I meant mnppsd not mnpsd. 

If I rename the column mnppsd to mnpaid in the casenode csv file in my exported zip-file and then read that zip file into R, then there is no problem and I can use the function form_status_summary(), which doesn't rely on additional report files (correct?).

**Comment by PatrickRWright** [comment]
If you need to change things manually in the export I wouldn't be too sure that everything is working as expected/designed so this would not be my approach of choice. Also, the `mnppsd` is definitely not the `mnpaid`. I had a quick look into the secuTrial manuals and found the following description for `mnppsd`:

`mnppsd, Patient pseudonym, The random patient pesudonym. This identifier may not be exported.`

The fact that it "may not be exported" confuses me a little since you seem to have an export containing it. In any case, I don't think this is related to the export language but rather to the export options more generally. Can you export the "Add-ID"? If you can and have not configured the ExportSearchTool do export it, then I suggest doing this which will likely solve your issue. If you can't export the "Add-ID" then I'm not sure I will be able to help you quickly since this may require some more extensive additions to `secuTrialR`.

**Comment by PatrickRWright** [comment]
I assume this is resolved.
