### ISSUE TITLE
incomplete dates

### ISSUE THREAD

**Issue by PatrickRWright** [SwissClinicalTrialOrganisation/secuTrialR#32]
They currently turn to `NA` and a warning is given for variables where not all dates were completely parsed.

This includes e.g. `mm.yyyy` types which are also currently not parsed. e.g. `tes05fuvisit$v_date_mmyyyy`

TES05 contains examples.

The current idea is not to implement any further functionality to remedy this issue but to write a section in the vignette which addresses this issue and point users into the directions of possible solutions. Research and examples prepared by @markomi can be found below.

**Comment by markomi** [comment]
I've done some reading on this and would like to share a few thoughts.

Basically, my impression is that although there are definitely ways to implement this functionality, it might be better not to do it within this package. Other opinions and ideas are very welcome. 

Long version:

First a description of the problem. 

```{r}
suppressMessages({
library(dplyr)
library(lubridate)
library(assertthat)
})
```


May the data.frame "dat" be representative of some data contained within a secuTrial export.
```{r}

dat <- data.frame(patient = c("1", "2", "3"),
                  informed_consent = c("20190316", "20190318", "20190402"), 
                  treatment_start = c("20190317", "201903", "2019"),
                  treatment_stop = c("20190328", "20190315", "20190701"))

```
 

If we use secuTrialR to import similar data contained in a secuTrial export, the result will be equivalent to the following
manipulation:


 
```{r}

dat <- dat %>% mutate(informed_consent.date = ymd(informed_consent),
                      treatment_start.date = ymd(treatment_start),
                      treatment_stop.date = ymd(treatment_stop))
dat
                      
```


dat$treatment_start.date has two rows that can't be converted to "Date". However, replacing those entries with "NA" is
not always the optimal strategy. We would like to come up with a better way of handling incomplete expressions of time.

If we use lubridate's parse_date_time(), we will get an approximation of incomplete dates to the start of the month. 
For example:

```{r}

dat <- dat %>% mutate(treatment_start.date.appx = parse_date_time(treatment_start, "y"),
                      treatment_start.date.appx = if_else(is.na(treatment_start.date.appx), 
                                                          parse_date_time(treatment_start, "ym"), 
                                                          treatment_start.date.appx),
                      treatment_start.date.appx = if_else(is.na(treatment_start.date.appx), 
                                                          parse_date_time(treatment_start, "ymd"), 
                                                          treatment_start.date.appx) %>% as.Date())
dat

```



So with this, we would approximate to the start of the month if day is missing, and to the start of the year,
if the month is missing. One could easily adapt this in order to impute incomplete dates to either start, end of middle of the month.

However, we need to consider that the approximation can lead to false conclusions. For example, the approximated
treatment_start.date.appx could be before the informed_consent.date.

```{r}

dat$treatment_start.date.appx[2] > dat$informed_consent.date[2]

dat$treatment_start.date.appx[3] > dat$informed_consent.date[3]

```

Similar incidents can happen, no mather if one imputes to start, middle or end of the month (or year).

An alternative strategy would be to impute to start / middle / end of a time interval which is study-dependent.

For example we could define the maximum possible interval for a treatment_start to occur to be within such an interval:

```{r}

interval(dat$informed_consent.date, dat$treatment_stop.date)

```


Furthermore, one would refine this interval based on the information about the treatment_start that we have available:
- if day is missing, start of the boundary is the first day of the month of treatment_start
- correspondingly for cases where only year is available.


However, we cannot extract the information about valid boundaries without the detailed knowledge of how the eCRF is implemented. Consider that for each column with incomplete dates, these boundary intervals might be different. 

My impression at the moment is that approximating dates should be left to secuTrialR users. I think warning the user that some dates could not be parsed should be sufficient.\
What do you guys think? If you have a good suggestion, I'd be up for implementing it.


Related R packages and issues:\
https://github.com/tidyverse/lubridate/issues/4 \
https://github.com/tidyverse/lubridate/issues/690 \
https://github.com/dgkf/parttime \

Related considerations:\
[Dubois and Hebert 2001](https://www.cambridge.org/core/services/aop-cambridge-core/content/view/F50311F9FFAB56176CDDC9FFBF66F655/S1041610202008025a.pdf/imputation_of_missing_dates_of_death_or_institutionalization_for_timetoevent_analyses_in_the_canadian_study_of_health_and_aging.pdf) \
[Bowman 2006](https://www.lexjansen.com/phuse/2006/po/PO11.pdf) \

**Comment by PatrickRWright** [comment]
Thank you @markomi for the detailed input on the matter. 
I had a feeling that:
- this may already have been addressed by other packages
- this may not be appropriate for secuTrialR

I agree that we should likely not include such a function in this package. However, what we can do is point users in the direction of solutions when the incomplete date warning comes up. I will probably do this in the vignette that I will eventually write. The examples and references that you supplied may be a part of that.

I will also remove the "Bug" label since I don't consider it appropriate anymore.

**Comment by aghaynes** [comment]
Thanks for thinking about this. "Do nothing" was also my approach in the stata version (although not so much due to thinking about it, more out of a havent-got-time-to-do-anything reason).

Would it be worthwhile creating an indicator for an introduced missing value? Basically the result of something like `!is.na(dat$date_orig) & is.na(dat$parsed_date)`.

As well as in the vignette, I would put something in the help file (`notes` field?) so that it's clear up front... I wouldn't pack too much into the warnings... verbose warnings are annoying IMO

**Comment by markomi** [comment]
Thanks to both for your replies!

@aghaynes when you talk about an indicator, you mean a new column with boolean values indicating that a date was not parsed correctly? Something like XXX.date.missing or XXX.date.partial?

**Comment by aghaynes** [comment]
> @aghaynes when you talk about an indicator, you mean a new column with boolean values indicating that a date was not parsed correctly? Something like XXX.date.missing or XXX.date.partial?

Exactly.

**Comment by PatrickRWright** [comment]
This can be closed when the vignette has been redone including the research that @markomi has done on the matter.

**Comment by PatrickRWright** [comment]
@aghaynes @markomi 
We have the export options `partial_date_handling` and `partial_date_string`. I think these are obsolete right?

**Comment by aghaynes** [comment]
They were carry-overs from the original version... I think we decided to not do anything about partial dates and let the user handle them didnt we? If so, yes, they're obsolete.

**Comment by PatrickRWright** [comment]
Ok, I'll remove them then.

**Comment by PatrickRWright** [comment]
@markomi would you like to formalize this into the README under a header "Incomplete date handling"? We could likely use that 1:1 in the vignette too?
