### ISSUE TITLE
data where data shouldn't be

### ISSUE THREAD

**Issue by aghaynes** [SwissClinicalTrialOrganisation/secuTrialR#5]
Say that we have variable Y that is only shown when variable X is yes. In participant AA, variable X is yes, and variable Y is entered. Sometime later, it is discovered that variable X is actually no. This is changed in the database. Secutrial, however, retains the value of variable Y without giving warnings.

It is perhaps possible that this is covered by the validation overview...

@PatrickRWright any idea?

**Comment by PatrickRWright** [comment]
Good observation. Technically I would consider this something to be changed within secuTrial itsself. I'll look into it.

**Comment by aghaynes** [comment]
Can you look into this?
 [ ] create some should-be-missing-but-not data (in CTU05?)
 [ ] create the relevant exports
 [ ] check for whether the issues flag in the validation export
 [ ] changes to `assess_form_variable_completeness`?

**Comment by PatrickRWright** [comment]
Quick Intro to my test. In CTU05 there is a form "allmedi". I can enter data into two freetext fields via catalogue. If I tick a checkbox "No further medication" these text fields disappear. I did the same type of test with a radio button based rule.

1. "Secutrial, however, retains the value of variable Y without giving warnings." If X ist set to "no" then the data in Y will be removed (-> its not in the export).

2. We probably do not need that export because secuTrial is doing what it is supposed to.

3. The issues flag in the validation export if I save and the fields are empty. If I "hide" the fields, they disappear from the validation overview. (all as expected)

4. No changes needed.

Fortunately it all seems to be working as you would expect it to.

**Comment by aghaynes** [comment]
great...then maybe it's an issue with the version of secutrial that we're using...

**Comment by aghaynes** [comment]
thanks for looking into it! :)

**Comment by aghaynes** [comment]
thanks for looking into it! :)
