### ISSUE TITLE
subset secuTrialdata object by patids

### ISSUE THREAD

**Issue by PatrickRWright** [SwissClinicalTrialOrganisation/secuTrialR#91]
**Is your feature request related to a problem? Please describe.**
Sometimes we may only want to apply the functions on a subset of the entire data (I have such tasks). e.g. only one type of morbidity in the patients of a study needs a certain plot.

 Subsetting the `secuTrialdata` object manually is tedious, error prone and likely requires in depth knowledge of the `secuTrialR` functions.

**Describe the solution you'd like**
Something like `subset(secuTrialdata, patid)` which will subset the entire `secuTrialdata` object and return an object only with data for the ids which are given to the subsetting function.

**Comment by markomi** [comment]
I would like to suggest implementing a few more features:
- subsetting based on inclusion or exclusion of parameters
- allowing subsetting based on parameters other than the patient id. for example center.

I'll start with the implementation now. @PatrickRWright @aghaynes if anything else comes to your mind, let me know.

**Comment by aghaynes** [comment]
Wouldn't this boil down to participant id anyway? 
Bear in mind that the package is for any user, many of which may have databases which do not prescribe to your (Basel's) standard variable/form naming conventions...(if Basel is anything like Bern, there's anyway variation around how forms are named, not so much inclusion/exclusion though).  
For me, anything beyond participant id is probably going to be too specific...

**Comment by PatrickRWright** [comment]
For the record: Ideally the subset of the `secuTrialdata` object should look like the cases which are being excluded were never registered. 

This can be tested e.g. by creating two exports in the ExportSearchTool. 
1. All centres
2. Only a subset of all centres

Subset the All centres export in R with the function you are making and check for differences to the subset created by the ExportSearchTool.

**Comment by markomi** [comment]
Thanks for sharing your thoughts. 

I was also thinking of only allowing subselection on a defined set of metadata variables, so that we can stay implementation-independent. I think pat_id and centre are the most common use cases. Nevertheless, I'll try to make it flexible, so that we can easily extend it.

As for inclusion/exclusion - not sure if I expressed it in the best possible way. What I meant is that I want to allow users to subset based on e.g. excluding certain patients, as well as based on subselecting only selected patients. This could be useful if one wants to e.g. select all patients but three in a cohort of a few hundred, or even thousands.
